name: GH Actions Testing First Name

on: [push]

jobs:
  test:
    name: GH Actions Test Name from Jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
