name: GH Actions Testing

on: [push]

jobs:
  test:
    name: GH Actions Test Name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
